dataloader:
  num_workers: 4
  shuffle: true
  wrapper:
    class: DynamicBatchWrapper
    complexity: n**2
    ubound_per_batch: 3000
dataset:
  train:
  - backbone_only: false
    class: PromptDataset
    mmap_dir: /data/private/jdp/PepGLAD/datasets/train_valid/processed
    specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/prompt_train_distance_index_augmentation.txt
    use_covariance_matrix: true
  - backbone_only: false
    class: PromptDataset
    mmap_dir: /data/private/jdp/PepGLAD/datasets/ProtFrag/processed
    specify_index: /data/private/jdp/PepGLAD/datasets/ProtFrag/processed/prompt_distance_index_augmentation.txt
    use_covariance_matrix: true
  valid:
    backbone_only: false
    class: PromptDataset
    mmap_dir: /data/private/jdp/PepGLAD/datasets/train_valid/processed
    specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/prompt_valid_distance_index_augmentation.txt
    use_covariance_matrix: true
model:
  autoencoder_ckpt: /home/jiangdapeng/PepGLAD/checkpoints/autoencoder.pth
  autoencoder_no_randomness: true
  class: Prompt_LDMPepDesign
  cutoff: 3.0
  diffusion_opt:
    trans_pos_type: Diffusion
    trans_seq_type: Diffusion
  dist_rbf: 32
  dist_rbf_cutoff: 7.0
  hidden_size: 128
  n_layers: 3
  n_rbf: 32
  num_steps: 100
trainer:
  class: LDMTrainer
  config:
    max_epoch: 1000
    metric_min_better: true
    optimizer:
      class: AdamW
      lr: 0.0001
    patience: 10
    save_dir: ./ckpts/LDM_codesign
    save_topk: 10
    scheduler:
      class: ReduceLROnPlateau
      factor: 0.6
      frequency: val_epoch
      min_lr: 5.0e-06
      mode: min
      patience: 3
    val_freq: 1
  criterion: Loss
