dataset:
  train:
    - class: PromptDataset
      mmap_dir: /data/private/jdp/PepGLAD/datasets/train_valid/processed
      specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/prompt_train_distance_index_augmentation.txt
      # specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/train_index.txt
      backbone_only: false
      # cluster: ./datasets/train_valid/train.cluster
      use_covariance_matrix: true
    - class: PromptDataset
      mmap_dir: /data/private/jdp/PepGLAD/datasets/ProtFrag/processed
      specify_index: /data/private/jdp/PepGLAD/datasets/ProtFrag/processed/prompt_distance_index_augmentation.txt
      backbone_only: false
      use_covariance_matrix: true
  valid:
    class: PromptDataset
    mmap_dir: /data/private/jdp/PepGLAD/datasets/train_valid/processed
    specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/prompt_valid_distance_index_augmentation.txt
    # specify_index: /data/private/jdp/PepGLAD/datasets/train_valid/processed/valid_index.txt
    backbone_only: false
    use_covariance_matrix: true

dataloader:
  shuffle: true
  num_workers: 4
  wrapper:
    class: DynamicBatchWrapper
    complexity: n**2
    # ubound_per_batch: 60000  # batch size ~32
    ubound_per_batch: 2500

trainer:
  class: LDMTrainer
  criterion: Loss
  config:
    max_epoch: 1000 # the best checkpoint should be obtained at around epoch 380
    save_topk: 10
    val_freq: 1
    save_dir: ./ckpts/LDM_codesign
    patience: 10
    metric_min_better: true

    optimizer:
      class: AdamW
      lr: 1.0e-4

    scheduler:
      class: ReduceLROnPlateau
      factor: 0.6
      patience: 3
      mode: min
      frequency: val_epoch
      min_lr: 5.0e-6

model:
  class: Prompt_LDMPepDesign
  autoencoder_ckpt: /home/jiangdapeng/PepGLAD/checkpoints/autoencoder.pth
  autoencoder_no_randomness: true
  hidden_size: 128
  num_steps: 100
  n_layers: 3
  n_rbf: 32
  cutoff: 3.0 # the coordinates are in standard space
  dist_rbf: 32
  dist_rbf_cutoff: 7.0
  # w: 5  # guidance strength
  # text_encoder: MLP #Attention: token level text embedding MLP: sentence level emb
  diffusion_opt:
    trans_seq_type: Diffusion
    trans_pos_type: Diffusion

# load_ckpt: /data/private/jdp/PepGLAD/checkpoints/codesign.ckpt

